name: platepal
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.4+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  hive_ce:
  hive_ce_flutter:
  flutter_bloc: ^8.1.6
  logger: ^2.4.0
  gap: ^3.0.1
  cached_network_image: ^3.4.1
  flutter_dotenv: ^5.1.0
  flutter_widget_from_html: ^0.15.3
  enhance_stepper: ^1.0.1
  draggable_home: ^1.0.5
  tap_to_expand: ^0.7.2
  autoscale_tabbarview: ^1.0.2
  share_plus: ^10.0.2
  shorebird_code_push: ^2.0.2
  dynamic_color: ^1.7.0
  flutter_colorpicker: ^1.1.0
  url_launcher: ^6.3.1
  retrofit: ^4.4.2
  get_it: ^8.0.3
  json_annotation: ^4.9.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_ce_generator:
  build_runner: ^2.4.12
  retrofit_generator: '>=8.0.0 <10.0.0'
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - shorebird.yaml