// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:platepal/config/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CaloriesEntityAdapter());
    registerAdapter(CategoryEntityAdapter());
    registerAdapter(ConfidenceRange95PercentEntityAdapter());
    registerAdapter(EntEntityAdapter());
    registerAdapter(ExtendedIngredientsEntityAdapter());
    registerAdapter(ImageAnalysisEntityAdapter());
    registerAdapter(LengthEntityAdapter());
    registerAdapter(MeasuresEntityAdapter());
    registerAdapter(MetricEntityAdapter());
    registerAdapter(NutritionEntityAdapter());
    registerAdapter(RandomRecipesEntityAdapter());
    registerAdapter(RecipeEntityAdapter());
    registerAdapter(RecipeIAEntityAdapter());
    registerAdapter(RecipeInstructionsEntityAdapter());
    registerAdapter(ResultEntityAdapter());
    registerAdapter(SearchRecipeEntityAdapter());
    registerAdapter(SimilarRecipesEntityAdapter());
    registerAdapter(StepEntityAdapter());
    registerAdapter(UsEntityAdapter());
  }
}
